on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (incl. submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}   # or a PAT if the submodule is private

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: gh-first-action1/package-lock.json  # <-- lockfile path

      - name: Sanity check (see files)
        run: |
          pwd
          ls -la
          ls -la gh-first-action1

      - name: Install deps
        working-directory: gh-first-action1
        run: npm ci

      - name: Run tests
        working-directory: gh-first-action1
        run: npm test