name: Test project
on: push
jobs: 
  test-job:
    runs-on: Ubuntu-latest
    steps: 
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install all dependencies
        run: npm install
      - name: Run tests
        run: npm test