name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print greetings
      run: echo "Hello the Asanga family"
    - name: Print goodby
      run: echo "I hope we all get together"
